import {NUMBERS,SUB_ROUNDS} from './more-math.js';
export const MORE_GAMES={
  subtract:{title:'Take-Away Cave',teacher:'otto',name:'Otto',skill:'Subtract within 10',greeting:"Hello, I'm Otto! Let's take some berries away and find how many are left.",watchIntro:'Taking away makes a group smaller. Watch Otto take two berries away from five.',prompt:'Look at the numbers. Tap to take berries away, then choose how many are left.',hint:'Cross out the berries we take away. Count only the berries that are left.',emptyHint:'There are no berries left. Zero means none.',retry:'Have another look. Count the berries that are left after we take some away.',finish:'Wonderful taking away! Five little puzzles complete. You can visit the town or play again!',demoStart:'Otto has five berries. He takes two berries away.',demoMove:'One berry away. Then one more. Two berries are taken away.',demoEnd:'Five take away two leaves three. Three berries are left!'},
  trail:{title:'Number Trail',teacher:'poppy',name:'Poppy',skill:'Order 0-20',greeting:"Hi, I'm Poppy! Hop along the number trail with me. Which number is missing?",watchIntro:'Numbers go in order. Each step on our trail adds one. Watch Poppy find a missing number.',prompt:'Count along the trail. Choose the number for the empty stepping stone.',hint:'Start with the first number. Count one more for each stepping stone.',retry:'Try counting the trail again. Each stepping stone is one more than the one before.',finish:'Lovely number hopping! Five trails explored. You can visit the town or play again!',demoStart:'Our trail starts at zero. Zero, one, then a missing number, then three.',demoMove:'One more than one is two. Put two on the empty stepping stone.',demoEnd:'Zero, one, two, three. The missing number is two!'},
  pattern:{title:'Pattern Parade',teacher:'luna',name:'Luna',skill:'Repeating patterns',greeting:"Hello, I'm Luna! Let's find the little group that repeats. What comes next in our parade?",watchIntro:'A repeating pattern uses the same little group again and again. Watch Luna find the next shape.',prompt:'Look for the group that repeats. Which shape comes next?',hint:'The coloured brackets show the repeating group. Start that group again when it ends.',retry:'Look at the repeating group again. Choose the shape that follows the last one.',success:'Yes! That shape keeps our repeating pattern going.',finish:'Wonderful pattern spotting! Five parades explored. You can visit the town or play again!',demoStart:'Circle, triangle. Circle, triangle. Circle, triangle.',demoMove:'Our repeating group is circle, triangle. The group starts again with a circle.',demoEnd:'A circle comes next. Circle, triangle repeats again!'},
  sort:{title:'Sort & Spot',teacher:'sunny',name:'Sunny',skill:'Sort by a rule',greeting:"Hi, I'm Sunny! Let's sort our treasures by colour, shape, or size. Tap every treasure that follows the rule.",watchIntro:'We can sort a collection by one rule. Watch Sunny choose every red treasure, whatever its shape or size.',prompt:'Read our sorting rule. Tap every treasure that follows the rule, then check your collection.',hint:'Look at one treasure at a time. Does it follow our rule? Keep all the treasures that do.',retry:'Check every treasure again. Choose all the treasures that follow our rule, and leave the others.',success:'Yes! You chose every treasure that follows our sorting rule.',finish:'Brilliant sorting! Five collections explored. You can visit the town or play again!',demoStart:'Our rule is red. Choose every red treasure.',demoMove:'These treasures are all red. Their shapes and sizes can be different.',demoEnd:'We chose all the red treasures, and left the blue and yellow treasures.'},
  measure:{title:'Measure Meadow',teacher:'luna',name:'Luna',skill:'Compare lengths',greeting:"Hello again! I'm Luna. Let's compare our ribbons. We line up their starts to find longer, shorter, or the same length.",watchIntro:'Line up the starts of two ribbons. Then compare their ends. Watch Luna find the longer ribbon.',longerPrompt:'The ribbons start at the same line. Which is longer? Or are they the same length?',shorterPrompt:'The ribbons start at the same line. Which is shorter? Or are they the same length?',hint:'Both ribbons start at the dotted line. The ribbon that reaches farther is longer.',sameHint:'Both ribbons start and end at the same places. They are the same length.',retry:'Check the starting line and the ends again. Which ribbon follows our question?',success:'Yes! You compared the ribbons from the same starting line.',finish:'Lovely measuring! Five ribbon pairs explored. You can visit the town or play again!',demoStart:'These ribbons start at the same line. The top ribbon reaches farther.',demoMove:'The top ribbon is longer. The bottom ribbon is shorter.',demoEnd:'Compare the ends after lining up the starts. That helps us compare lengths!'}
};
export const subtractionSuccess=(a,b)=>`${NUMBERS[a]} take away ${NUMBERS[b]} leaves ${NUMBERS[a-b]}. Lovely!`;
export const trailSuccess=n=>`Yes! The missing number is ${NUMBERS[n]}.`;
export const MORE_NARRATION=[];
for(const game of Object.values(MORE_GAMES)){
  for(const key of ['greeting','watchIntro','prompt','longerPrompt','shorterPrompt','hint','emptyHint','sameHint','retry','success','finish','demoStart','demoMove','demoEnd'])if(game[key])MORE_NARRATION.push({character:game.teacher,text:game[key],speed:.96});
  for(const text of ['We can take a little pause. Press Watch to start again.',"Now it's your turn! Press My turn to play."])MORE_NARRATION.push({character:game.teacher,text,speed:.96});
}
for(const [a,b] of SUB_ROUNDS)MORE_NARRATION.push({character:'otto',text:subtractionSuccess(a,b),speed:.96});
for(let n=0;n<=20;n++)MORE_NARRATION.push({character:'poppy',text:trailSuccess(n),speed:.96});
